# Generated by Django 4.1 on 2023-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=20)),
                ('tax_category', models.CharField(choices=[('Resposable Inscripto', 'Responsable Inscripto'), ('Monotributista', 'Monotributista')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
