# Generated by Django 4.1 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providers',
            options={'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
        migrations.AlterField(
            model_name='providers',
            name='address',
            field=models.CharField(max_length=400, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='tax_category',
            field=models.CharField(choices=[('Resposable Inscripto', 'Responsable Inscripto'), ('Monotributista', 'Monotributista')], max_length=50, verbose_name='categogia fiscal'),
        ),
    ]
