# Generated by Django 4.1 on 2023-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
