# Generated by Django 4.1 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menus_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AddField(
            model_name='menus',
            name='image',
            field=models.ImageField(default='', upload_to='menus', verbose_name='imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre del menu'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='price',
            field=models.FloatField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='stock'),
        ),
    ]
