# Generated by Django 4.1 on 2023-02-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menus_options_menus_image_alter_menus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
