# Generated by Django 4.1 on 2023-01-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Transfer', 'Transfer'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=8)),
            ],
        ),
    ]
