# Generated by Django 4.1 on 2023-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_deliveries_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Transfer', 'Transfer'), ('Cash', 'Cash')], max_length=8),
        ),
    ]
