# Generated by Django 4.1 on 2023-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliveries_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=4),
        ),
    ]
