# Generated by Django 4.1 on 2023-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_alter_deliveries_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=8),
        ),
    ]
