# Generated by Django 4.1 on 2023-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_deliveries_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliverys'},
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='client',
            field=models.CharField(max_length=100, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='menu',
            field=models.CharField(max_length=100, verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=13, verbose_name='metodo de pago'),
        ),
    ]
